# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title: Breno Bragalha
author:
  name: Breno Bragalha
  email: bragalhabreno.dev@icloud.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  Awesome description for your new site here.

# If you want to link only specific pages in your header, use this and add the path to the pages in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
# date_format: "%b %d, %Y"

# Social Media Links
# Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
#
# Entry keys:
# * title     Tooltip rendered on hovering over icon.
# * icon      Font Awesome icon id. `github` corresponds to `fa-github`.
# * url       Full URL of social profile.
social_links:
  - title: GitHub
    icon: github
    url: "https://github.com/brenobragalha"

# Skins
#
# Entry keys:
# * auto
# * classic
# * dark
skin: auto
