plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Breno Bragalha
author:
  name: Breno Bragalha
  email: bragalhabreno.dev@icloud.com

description: >-
  I'm an iOS Engineer passionate about the Apple ecosystem and Swift. I write articles, create high-quality apps and tools, and always focus on building great products.

social_links:
  - title: GitHub
    icon: github
    url: "https://github.com/brenobragalha"
    icon_type: brands
  - title: X
    icon: x-twitter
    url: "https://x.com/brenobragalha"
    icon_type: brands
  - title: LinkedIn
    icon: linkedin
    url: "https://www.linkedin.com/in/"
    icon_type: brands
  - title: Mail
    icon: envelope
    url: "mailto:bragalhabreno.dev@icloud.com"
    icon_type: solid
  - title: RSS
    icon: rss
    url: "https://brenobragalha.github.io/feed.xml"
    icon_type: solid

header_pages:
  - about.md

skin: auto
show_excerpts: true
paginate: 5
# date_format: "%b %d, %Y"
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
